name: test-conda-env-py3-macos
channels:
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy
- conda-forge::sympy
- scipy
- pocl
- islpy
- pyopencl
- python>=3.6
- symengine=0.3.0
- python-symengine=0.3.0
- pyfmmlib
# for OpenMP support in pyfmmlib
- libgfortran>=3.0.1
- clangdev
- openmp
- cython
# things not in here: loopy boxtree pymbolic meshmode sumpy
