name: test-conda-env-py3-macos
channels:
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy
- conda-forge::sympy
- scipy
- pocl=1.0
- islpy
- pyopencl
- python=3.6
- symengine=0.3.0
- python-symengine=0.3.0
- osx-pocl-opencl
- pyfmmlib
- gcc
- cython
# things not in here: loopy boxtree pymbolic meshmode sumpy
